# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Machine Learning 4 Me
tagline:             ''
description:         'As I learn more about machine learning hopefully you can too.'
url:                 http://machinelearning4me.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Rick Jaramillo
  url:               https://twitter.com/ml4me_io
  email:             me@machinelearning4me.io

# Custom vars
version:             1.0.0

# Plugins
plugins:
   - jekyll-paginate
   - jekyll-feed
